name: Deploy HelloWorld iFlow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get OAuth Token
        id: auth
        env:
          CLIENT_ID: ${{ secrets.BTP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.BTP_CLIENT_SECRET }}
          TOKEN_URL: ${{ secrets.BTP_TOKEN_URL }}
          API_URL: ${{ secrets.BTP_API_URL }}
        run: |
          RESPONSE=$(curl -s \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -X POST \
            "$TOKEN_URL?grant_type=client_credentials")

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Deploy HelloWorld
        env:
          API_URL: ${{ secrets.BTP_API_URL }}
        run: |
          curl -X POST \
          "$API_URL/api/v1/DeployIntegrationDesigntimeArtifact?Id='HelloWorld'&Version='active'" \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/json"