name: Deploy CPI iFlow

on:
  workflow_dispatch:
    inputs:
      package_id:
        description: 'Package ID'
        required: true
        default: 'DevOpsDemo'

      iflow_id:
        description: 'iFlow ID'
        required: true
        default: 'HelloWorld'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get OAuth Token
        env:
          CLIENT_ID: ${{ secrets.BTP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.BTP_CLIENT_SECRET }}
          TOKEN_URL: ${{ secrets.BTP_TOKEN_URL }}
          API_URL: ${{ secrets.BTP_API_URL }}
        run: |
          RESPONSE=$(curl -s \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -X POST \
            "$TOKEN_URL?grant_type=client_credentials")

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Deploy iFlow
        env:
          API_URL: ${{ secrets.BTP_API_URL }}
          IFLOW_ID: ${{ github.event.inputs.iflow_id }}
        run: |
          echo "Deploying $IFLOW_ID"

          curl -X POST \
            "$API_URL/api/v1/DeployIntegrationDesigntimeArtifact?Id='$IFLOW_ID'&Version='active'" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/json"